package com.example.util

object Localization {

    enum class Lang {
        EN, UR
    }

    private val translations = mapOf(
        "app_title" to Pair("Tariq Shoes & Wholesale Dealer", "طارق شوز اینڈ ہول سیل ڈیلر"),
        "dashboard" to Pair("Dashboard", "ڈیش بورڈ"),
        "products" to Pair("Products", "پروڈکٹس"),
        "sales" to Pair("Sales", "سیلز"),
        "customers" to Pair("Customers", "کسٹمرز"),
        "reports" to Pair("Reports", "رپورٹس"),
        "settings" to Pair("Settings", "ترتیبات"),
        "today_sales" to Pair("Today's Sales", "آج کی فروخت"),
        "today_profit" to Pair("Today's Profit", "آج کا منافع"),
        "today_orders" to Pair("Today's Orders", "آج کے آرڈرز"),
        "total_products" to Pair("Total Products", "کل پروڈکٹس"),
        "total_stock" to Pair("Total Stock", "کل اسٹاک"),
        "total_customers" to Pair("Total Customers", "کل کسٹمرز"),
        "total_receivable" to Pair("Receivable / Credit", "وصولی / ادھار"),
        "low_stock_products" to Pair("Low Stock Alert", "کم اسٹاک وارننگ"),
        "recent_sales" to Pair("Recent Sales", "حالیہ فروخت"),
        "add_product" to Pair("Add Product", "پروڈکٹ شامل کریں"),
        "new_sale" to Pair("New Sale", "نئی فروخت"),
        "scan_qr" to Pair("Scan QR", "کیو آر اسکین کریں"),
        "add_customer" to Pair("Add Customer", "کسٹمر شامل کریں"),
        "purchase_stock" to Pair("Purchase Stock", "اسٹاک خریداری"),
        "stock_management" to Pair("Stock Management", "اسٹاک مینجمنٹ"),
        "suppliers" to Pair("Suppliers", "سپلائرز"),
        "quick_sale" to Pair("Quick Sale", "فوری فروخت"),
        "product_id" to Pair("Product ID", "پروڈکٹ کوڈ"),
        "product_name" to Pair("Product Name", "پروڈکٹ کا نام"),
        "category" to Pair("Category", "کیٹیگری"),
        "design" to Pair("Design / Model", "ڈیزائن / ماڈل"),
        "brand" to Pair("Brand", "برانڈ"),
        "size" to Pair("Size", "سائز"),
        "color" to Pair("Color", "رنگ"),
        "purchase_price" to Pair("Purchase Price", "خرید قیمت"),
        "retail_price" to Pair("Retail Price", "پرچون قیمت"),
        "wholesale_price" to Pair("Wholesale Price", "ہول سیل قیمت"),
        "quantity" to Pair("Quantity", "تعداد"),
        "supplier" to Pair("Supplier", "سپلائر"),
        "description" to Pair("Description", "تفصیل"),
        "min_stock" to Pair("Min Stock Level", "کم سے کم اسٹاک"),
        "save_product" to Pair("Save Product", "پروڈکٹ محفوظ کریں"),
        "edit_product" to Pair("Edit Product", "ترمیم کریں"),
        "delete_product" to Pair("Delete Product", "حذف کریں"),
        "view_product" to Pair("View Product", "پروڈکٹ دیکھیں"),
        "search_hint" to Pair("Search shoes, ID, customer, barcode...", "تلاش کریں شوز، کوڈ، کسٹمر..."),
        "cash" to Pair("Cash", "نقد"),
        "credit" to Pair("Credit", "ادھار"),
        "partial_payment" to Pair("Partial Payment", "جزوی ادائیگی"),
        "complete_sale" to Pair("Complete Sale", "سیل مکمل کریں"),
        "subtotal" to Pair("Subtotal", "کل رقم"),
        "discount" to Pair("Discount", "رعایت"),
        "grand_total" to Pair("Grand Total", "ٹوٹل رقم"),
        "paid_amount" to Pair("Paid Amount", "ادا شدہ رقم"),
        "remaining_amount" to Pair("Remaining Balance", "بقایا رقم"),
        "profit" to Pair("Profit", "منافع"),
        "invoice_number" to Pair("Invoice #", "انوائس نمبر"),
        "date" to Pair("Date", "تاریخ"),
        "customer_name" to Pair("Customer Name", "گاہک کا نام"),
        "customer_phone" to Pair("Customer Phone", "گاہک کا فون"),
        "save_pdf" to Pair("Save PDF", "پی ڈی ایف بنائیں"),
        "print" to Pair("Print", "پرنٹ کریں"),
        "share" to Pair("Share", "شیئر کریں"),
        "whatsapp" to Pair("WhatsApp", "واٹس ایپ"),
        "phone" to Pair("Phone", "فون"),
        "address" to Pair("Address", "پتہ"),
        "backup" to Pair("Backup Data", "بیک اپ ڈیٹا"),
        "restore" to Pair("Restore Data", "ڈیٹا بحال کریں"),
        "admin_security" to Pair("Admin Security", "ایڈمن سیکیورٹی"),
        "admin_pin" to Pair("Admin PIN", "ایڈمن پن"),
        "enter_pin" to Pair("Enter Admin PIN", "ایڈمن پن درج کریں"),
        "language" to Pair("Language", "زبان"),
        "dark_mode" to Pair("Dark Mode", "ڈارک موڈ"),
        "light_mode" to Pair("Light Mode", "لائٹ موڈ"),
        "system_mode" to Pair("System Default", "سسٹم کا ڈیفالٹ"),
        "low_stock" to Pair("LOW STOCK", "کم اسٹاک"),
        "out_of_stock" to Pair("OUT OF STOCK", "اسٹاک ختم"),
        "in_stock" to Pair("IN STOCK", "اسٹاک موجود"),
        "print_qr_label" to Pair("Print QR Label", "کیو آر لیبل پرنٹ"),
        "daily_sales" to Pair("Daily Sales", "روزانہ فروخت"),
        "weekly_sales" to Pair("Weekly Sales", "ہفتہ وار فروخت"),
        "monthly_sales" to Pair("Monthly Sales", "ماہانہ فروخت"),
        "yearly_sales" to Pair("Yearly Sales", "سالانہ فروخت"),
        "profit_report" to Pair("Profit Report", "منافع رپورٹ"),
        "stock_report" to Pair("Stock Report", "اسٹاک رپورٹ"),
        "payments_report" to Pair("Payments & Credit", "ادائیگی اور ادھار"),
        "record_payment" to Pair("Record Payment", "ادائیگی درج کریں"),
        "delete_samples" to Pair("Delete Sample Products", "نمونہ پروڈکٹس ڈیلیٹ کریں"),
        "sample_data_info" to Pair("3 sample footwear items loaded for initial demonstration.", "ابتدائی مظاہرے کے لیے 3 نمونے کے جوتے شامل ہیں۔"),
        "confirm_delete" to Pair("Are you sure you want to delete?", "کیا آپ واقعی حذف کرنا چاہتے ہیں؟"),
        "confirm_restore" to Pair("Restore will merge and update data. Proceed?", "ڈیٹا بحال کرنے سے تبدیلیاں لاگو ہوں گی۔ آگے بڑھیں؟"),
        "stock_insufficient" to Pair("Insufficient stock available!", "اسٹاک میں مطلوبہ تعداد موجود نہیں!"),
        "sale_success" to Pair("Sale completed successfully!", "فروخت کامیابی سے مکمل ہو گئی!"),
        "wholesale_dealer" to Pair("Wholesale Dealer", "ہول سیل ڈیلر"),
        "karachi_location" to Pair("Motorway site, Khyber Gate, Karachi", "موٹروے سائٹ، خیبر گیٹ، کراچی")
    )

    fun tr(key: String, lang: String = "EN"): String {
        val entry = translations[key] ?: return key
        return if (lang.equals("UR", ignoreCase = true)) entry.second else entry.first
    }
}
